### PR TITLE
Create code.html

### PR DESCRIPTION
**Pull request by LukyVj**
Example for: https://github.com/zserge/awfice/issues/12

### CODE REVIEW

**Comment by istudyatuni** [comment]
Not critical, but maybe add indents by pressing TAB?

**Comment by LukyVj** [comment]
Not sure I understand your request

**Comment by istudyatuni** [comment]
When I press tab, i switched to the next field (for example, if i write CSS, and press tab, i toggle to js field)

**Comment by LukyVj** [comment]
Ok I see what you mean. I think a simple `tabindex="-1"` would do the trick.

Ill implement it as soon as I can.

**Comment by LukyVj** [comment]
Allright, so I won't do it as the solution requires a little bit more Javascript, and I think the goal of this project is to use the smallest weight possible. Max I could do is to peventDefault() the tab, buy implementing a tab behavior on these few lines would make them too big to my appreciation.

**Comment by LukyVj** [comment]
@istudyatuni Well, I ended up doing it :D Not sur if the new weight is worth it. I'll let @zserge decide about that! :D

**Comment by istudyatuni** [comment]
A good choice :)

**Comment by LukyVj** [comment]
<table>
<tr>
	<td>Screenshot 2020-10-19 at 10 58 31</td>
	<td> Awfice code editor gif </td>
</table>

**Comment by xrat** [comment]
So, we now have an awfice code editor that we can use to test awfice code. How cool is that!

**Comment by LukyVj** [comment]
I wanted to make it responsive but hey, goos start :D

**Comment by zserge** [comment]
Wow. Looks really good, and I'm convinced to merge it, however, why does `wc -c` report the byte numbers in such a weird right-aligned way in the readme?

**Comment by LukyVj** [comment]
Dude, I have no idea, I noticed it as well. Probably due to my workstation config ( which I rather keep as it as :D ) But yeah; sorry for the extra spaces 🙈

**Comment by LukyVj** [comment]
So, @zserge are you gonna merge this or do you have any further requests?

**Comment by Ynewtime** [comment]
How about replace `\t` with two spaces? I know it's about code style though, `\t` might be a little too much spaces there. I tried replacing `\t` with two spaces and it looks a bit better.

```js
data:text/html,<title>Code</title> <body oninput="i.srcdoc=h.value+'<style>'+c.value+'</style><script>'+j.value+'</script>'" > <style> textarea, iframe { width: 100%; height: 50%; } body { margin: 0; } textarea { width: 33.33%; font-size: 18px; padding: 0.5em; }</style ><textarea placeholder="HTML" id="h"></textarea ><textarea placeholder="CSS" id="c"></textarea ><textarea placeholder="JS" id="j"></textarea> <iframe id="i"></iframe> <script> document.querySelectorAll('textarea').forEach((t) => t.addEventListener('keydown', function (t) { var e, s; 'Tab' == t.key && (t.preventDefault(), (e = this.selectionStart), (s = this.selectionEnd), (this.value = this.value.substring(0, e) + '  ' + this.value.substring(s)), (this.selectionStart = this.selectionEnd = e + 2)); }) ); </script> </body>
```

**Comment by LukyVj** [comment]
Done :) 

I'll let you do whatever you want with it!

**Pull request merged**
